library/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
from django.contrib.auth.decorators import login_required, permission_required

from apps.book.views import BookListView, BookLeaseListView
from apps.book.views import BookLeaseDetailView, BookDetailView 
from apps.book.views import book_delete
from apps.book.views import get_book
from apps.book.views import edit_book
from apps.book.views import borrow_book, lend_book, admin_response
from apps.libraryuser.views import login, logout
from apps.libraryuser.views import HomeView
from apps.libraryuser.models import Fellow
from apps.libraryuser.tasks import send_admin_mail

urlpatterns = patterns ('',
    url('', include('social.apps.django_app.urls', namespace='social')),
    url(r'^$', HomeView.as_view(), name='home'),
    url(r'^detail/(?P<pk>[-_\w]+)', login_required(BookDetailView.as_view()), name='book-detail'),
    url(r'^book-detail/(?P<pk>[-_\w]+)', login_required(BookLeaseDetailView.as_view()), name='booklease-detail'),
    url(r'^home/$', login_required(BookListView.as_view()), name='book-list'),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^login/$', login, name='login'),
    url(r'^logout/$', logout, name='logout'),
    url(r'^book-status/$', login_required(BookLeaseListView.as_view()), name='booklease-list'),
    url(r'^add-book/$', get_book, name='add-book'),
    url(r'^edit-book/(?P<id>\d+)/$', edit_book, name='edit-book'),
    url(r'^borrow/(?P<id>\d+)/$', borrow_book, name='borrow-book'),
    url(r'^lend-book/(?P<id>\d+)/$', lend_book, name='lend-book'),
    url(r'^delete/(?P<pk>\d+)$', book_delete, name='book_delete'),
    url(r'^send-mail/$', send_admin_mail, name='send_mail'),
    url(r'^admin-response/$', admin_response, name="admin_response"),
)
   

apps/book/models.py
from django.db import models
from datetime import date, timedelta
import time
from dateutil.relativedelta import relativedelta
from django.utils import timezone
from django.contrib.auth.models import User
from apps.libraryuser.models import StaffUser, Fellow

Categories = (
         ("Science fiction", "Science fiction"),
         ("Satire", "Satire"),
         ("Drama", "Drama"),
         ("Action and Adventure","Action and Adventure"),
         ("Romance", "Romance"),
         ("Mystery", "Mystery"),
         ("Horror", "Horror"),
         ("Self help", "Self help"),
         ("Guide", "Guide"),
         ("Travel", "Travel"),
         ("Children's", "Children's"),
         ("Religious", "Religious"),
         ("Science", "Science"),
         ("History", "History"),
         ("Math", "Math"),
         ("Anthologies", "Anthologies"),
         ("Poetry", "Poetry"),
         ("Encyclopedias", "Encyclopedias"),
         ("Dictionaries", "Dictionaries"),
         ("Comics", "Comics"),
         ("Art", "Art"),
         ("Cookbooks", "Cookbooks"),
         ("Diaries", "Diaries"),
         ("Journals", "Journals"),
         ("Prayer books", "Prayer books"),
         ("Series", "Series"),
         ("Programming", "Programming"),
         ("Biographies", "Biographies"),
         ("Autobiographies", "Autobiographies"),
         ("Fantasy", "Fantasy"),
    )

class Book(models.Model):
    title = models.CharField(max_length=50, blank=False)
    author = models.CharField(max_length=100, blank=False)
    isbn_number = models.CharField(max_length=100, unique=True)
    date_recieved = models.DateField(auto_now_add=True)
    quantity = models.PositiveIntegerField(default=1)
    source = models.CharField(max_length=50)
    category = models.CharField(max_length=150, choices=Categories)

    def get_num_available_book(self):
        available = self.quantity
        if available > 0:
            total_leased = self.book_leases.all().count()
            available = available - total_leased
        return available
    
    def get_book_request(self):
        requests = self.bookborrowrequest_set.all()
        return [i.borrower.username for i in requests]

    def get_book_deadline(self):
        leases = self.book_leases.all()
        return {lease.borrower.email:lease.days_due() for lease in leases}

    num_book_available = property(get_num_available_book)
        
    def __unicode__(self): 
        return '{}'.format(self.title)


def now():
    return date.today()


def get_deadline():
    return now() + timedelta(days=14)


class BookBorrowRequest(models.Model):
    borrower = models.ForeignKey(User)
    book_name = models.ForeignKey(Book)
    is_allowed = models.BooleanField(default=False)

    # def __unicode__(self):
    #     return self.borrower

class BookLease(models.Model):
    book = models.ForeignKey(Book, related_name='book_leases')
    borrower = models.ForeignKey(Fellow)
    borrowed_date = models.DateField(auto_now_add=True)
    due_date = models.DateField(default=get_deadline)
    returned = models.NullBooleanField()

    def check_due(self):
        today = now()
        return self.due_date - today 

    def book_is_due(self):
        due_diff = self.check_due()
        if due_diff.total_seconds() <= 0:
            return "due"
        elif due_diff.days <= 2:
            return "about"

    def days_due(self):
        due_diff = self.check_due()
        return abs(due_diff.days)

    def __unicode__(self): 
        return '{}'.format(self.book)

templates/base.html
{% load staticfiles %}

<!DOCTYPE html>
<html>
<head>
    <meta charset='utf-8'>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1.0, user-scalable=no"/>
    <title>
        {% block title %}
            Andela Library
        {% endblock title %}
    </title>
    {% block styling %}
        <link rel="stylesheet" type="text/css" href="{% static 'styles/reset.css' %}">
        <link rel="stylesheet" type="text/css" href="{% static 'styles/style.css' %}">
        <link rel="stylesheet" type="text/css" href="{% static 'materialize/css/materialize.css'%}">
        <link rel="stylesheet" type="text/css" href="{% static 'styles/chosen.css' %}">
        <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css">
    {% endblock %}
</head>
<body>
    <div id="wrapper">
        <header>
            <ul id="dropdown1" class="dropdown-content">
                <li class='drop-down'><a href="{% url 'add-book' %}">Add a Book</a></li>
                <li class='drop-down'><a href="{% url 'booklease-list' %}">Track Books</a></li>
                <li class="divider"></li>
                <li class='drop-down'><a href="{% url 'logout' %}">Logout</a></li>
            </ul>
            <nav class = "navbar">
                <div class="wrapper" style="margin-right: 194px; padding-top: 32px;">
                    <a href="{% url 'book-list' %}"><h3 id="folay">Folay</h3></a>
                    <ul>
                        {% if request.user.is_authenticated %}
                          {% if request.user.is_staff %}
                            <li><a href="{% url 'book-list' %}">Home</a></li>
                            <li><a href="#" class='dropdown-button' data-beloworigin="true" data-activates='dropdown1' style="text-transform: capitalize;">{{ request.user.username }}<i class="mdi-navigation-arrow-drop-down right"></i></a></li>
                            <ul id='dropdown1' class='dropdown-content'>

                            </ul>
                          {% else %}
                            <li><a href="{% url 'book-list' %}">Home</a></li>
                            <li><a href="{% url 'book-list' %}">{{ request.user.username }}</a></li>
                            <li><a href="{% url 'logout' %}">Logout</a></li>
                          {% endif %}
                        {% else %}
                            <li><a href="{% url 'login' %}">Login</a></li>
                        {% endif %}
                    </ul>
                </div>
            </nav>
        </header>
            <div id="content">
                {% block content %}
                    <div id="home-content">    
                        <div class="home-body">
                            <p class="flow-text">
                                "A library is the delivery room for the birth of ideas, <br>a place,<br> where history comes to life." 
                            </p>  
                            <br />
                            <a class="waves-effect waves-light btn visit" href="{% url 'login' %}"><i class="mdi-action-exit-to-app right"></i>VISIT</a>
                        </div>
                    </div>
                {% endblock %}
            </div>  
                {% block footer %}        
              <footer id="footer">
                    <div class="footer-text">
                      <div class="footer-container">
                        Made in <strong>Lagos </strong>by Andela Fellows.
                      </div>
                    </div>
              </footer>
            {% endblock %}
         </div>
    {% block javascript %}
        <script type="text/javascript" src="{% static 'js/jquery.js' %}"></script>
        <script type="text/javascript" src="{% static 'materialize/js/materialize.js' %}"></script>
    {% endblock %}
    <script type="text/javascript" src="{% static 'js/jquery-migrate-1.2.1.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/chosen.jquery.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/common.js' %}"></script>

    {% block js %}
        
    {% endblock %}
</body>
</html>

templates/book_edit.html
{% extends "index.html" %}
{% block content %}

<div class="col s12 m3 l12 login-card add-book">
    <div class="card add-book-card">
        <div class="card-content">
        <h4>Edit Book</h4>
        <div class="add-form">
          <form class="book-add" method="post">
          {% csrf_token %}
          {{form}}
            <!--<input type="hidden" name="id" value="{{book.id}}" />
            {{form.title.errors}}
            <label for="id_title">Book Title: </label>
            <input id = "id_title" type="text" name="title" value="{{ book.title }}">
            {{form.quantity.errors}}
            <label for="id_quantity">Book Quantity: </label>
            <input id = "id_quantity" type="number" name="quantity" value="{{ book.quantity }}">
            {{form.author.errors}}
            <label for="id_author">Book Author: </label>
            <input id = "id_author" type="text" name="author" value="{{ book.author }}">
            {{form.source.errors}}
            <label for="id_source">Source Name: </label>
            <input id = "id_source" type="text" name="source" value="{{ book.source }}">
            {{form.isbn_number.errors}}
            <label for="id_isbn_number">Books ISBN: </label>
            <input id = "id_isbn_number" type="text" name="isbn_number" value="{{ book.isbn_number }}">
            {{form.category.errors}}
            <label for="id_category">Book Category: </label>
            <input id = "id_category" type="text" name="category" value="{{ book.category }}">-->

            <div>
                <button class="btn waves-effect waves-light edit-button" type="submit" name="action">Save Changes
                  <i class="mdi-content-send right"></i>
                </button>
                <a href="/home/" class="cancel-edit">Cancel</a>  
            </div>
          </form>
        </div>
        </div>
    </div>  
</div>
{% endblock content %}

templates/book_new.html
{% extends "index.html" %}
{% block content %}
<div class="col s12 m3 l12 login-card add-book">
    <div class="card add-book-card">
        <div class="card-content">
        <h4>Add Book</h4>
        <div class="add-form">
          <form class="book-add" method="post">
          {% csrf_token %}
            <input type="hidden" name="id" value="{{book.id}}" />
            <label for="id_title">Book Title: </label>
            {{form.title.errors}}
            <input id = "id_title" type="text" name="title" value="{{ current_title }}">
            <label for="id_quantity">Book Quantity: </label>
            {{form.quantity.errors}}
            <input id = "id_quantity" type="number" name="quantity" value="{{ current_quantity }}">
            <label for="id_author">Book Author: </label>
            {{form.author.errors}}
            <input id = "id_author" type="text" name="author" value="{{ current_author }}">
            <label for="id_source">Source Name: </label>
            {{form.source.errors}}
            <input id = "id_source" type="text" name="source" value="{{ current_source }}">
            <label for="id_isbn_number">Books ISBN: </label>
            {{form.isbn_number.errors}}
            <input id = "id_isbn_number" type="text" name="isbn_number" value="{{ current_isbn_number }}">
            <label for="id_category">Book Category: </label>
            {{form.category.errors}}
            {{form.category}}
            <div>
                <button class="btn waves-effect waves-light add-button" type="submit" name="action">Add Book
                  <i class="mdi-content-send right"></i>
                </button>
                <a href="/home/" class="cancel">Cancel</a>  
            </div>
          </form>
        </div>
        </div>
    </div>  
</div>
{% endblock content %}

{% block local_js %}
    
    <script type="text/javascript">
        $(document).ready(function() {
             var date = new Date()
             var get_book_date = date.toISOString().substring(0, 10),
             recieve = document.querySelector('#id_date_recieved');
             recieve.value = get_book_date;
        });
    </script>
{% endblock local_js %}

templates/borrow_book.html
{% extends "index.html" %}
{% block content %}
<div class="col s12 m3 l12 login-card">
    <div class="card add-book-card">
        <div class="card-content">
            <h4>Lend Book</h4>
            <div class="add-form">
                <label for="id_book_title">Book:</label>
                <div id="id_book_title">{{ book.title }}</div>
                <form class="book-add" method="post">
                   {% csrf_token %}
                   {{ form }}
                   <button class="btn waves-effect waves-light lend-button" type="submit" name="action">Lend Book
                  <i class="mdi-content-send right"></i>
                </button>
                </form> 
                <div class="modal-footer">
                  <a href="/home/" class=" modal-action modal-close waves-effect waves-green btn-flat cancel">Cancel</a>
                </div>
            </div>
        </div>
    </div>   
</div>
{% endblock content %}
{% block local_js %}
{% endblock local_js %}

templates/delete_book.html
{% extends 'index.html' %}

{% block content %}
Hey, are you sure you want to delete {{ object.title }}?
<form method="post">
  {% csrf_token %}
<a href="{% url 'book-index' %"><button>Yeap, I'm sure.</button></a>
<a href="/detail/{{object.id}}">Cancel</a>
</form>
{% endblock %}

templates/index.html
{% extends "base.html" %}
{% load staticfiles %}

<div class="col s9 books">
    {% block content %}

    {% endblock content %}
</div>

{% block local_js %}
<script>
$(document).ready(function() {
  // the "href" attribute of .modal-trigger must specify the modal ID that wants to be triggered
  $('.modal-trigger').leanModal();
});
</script>
{% endblock %}

templates/login.html
{% extends 'index.html' %}

{% block img %}
{% endblock %}

{% block search %}
{% endblock %}

{% block content %}
    <div class="row login-page">
    <div class="col s12 m3 l6 login-card">
        <div class="card login-card-form">
          <div class="card-content black-text">
              <div class="form-wrapper center-align">
                <h4>Sign In</h4>

                {% if form.errors %}
                  <p class="'error">Sorry, invalid username or password</p>
                {% endif %}

                <form class="col s12 m12 l12 #26a69a login-form" action="{% url 'login' %}" method="POST">
                {% csrf_token %}
                
                  <div class="row">
                    <div class="input-field col s12">
                      <input id="username" type="text" class="validate username" name="username">
                      <label for="username">Username</label>
                    </div>
                  </div>

                  <div class="row">
                    <div class="input-field col s12">
                      <input id="password" type="password" class="validate password" name="password">
                      <label for="password">Password</label>
                    </div>
                  </div>
                    <div class="buton">
                       <button class="btn waves-effect #26a69a lighten-2 waves-light login-botton" type="submit" name="action" value="login">Login as Admin<i class="fa fa-lock right"></i></button>
                    </div><br />
                      <div class="user-login">
                         <a class="visit" href="{% url 'social:begin' 'google-oauth2' %}"><span>Not an Admin?</span> Login as User</a>
                      </div>
                    </div>
                  </div>
                </form>
              </div>

          </div>

        </div>
    </div>
  </div>
{% endblock %}
{% block footer %}
{% endblock %}

templates/login_error.html
{% extends 'index.html' %}

{% block img %}
{% endblock %}

{% block search %}
{% endblock %}
{% block content %}
  <div class="card medium error-card">
    <div class="card-image waves-effect waves-block waves-light">
      <img class="activator" src="https://c1.staticflickr.com/3/2879/12033379296_e6f4aca73e_z.jpg" alt="Smiley face" height="400" width="4">
    </div>
    <div class="card-content">
      <span class="card-title activator grey-text text-darken-4">You are probably not an Admin.</span>
    </div>
      <a class="visited" href="{% url 'social:begin' 'google-oauth2' %}">Login as User</a><span><a href="{% url 'login' %}" class="back-link"><i class="fa fa-arrow-left"></i> Back to admin login</span></a>
  </div>
{% endblock %}
{% block footer %}
{% endblock %}

templates/signup.html
{% extends 'index.html' %}

{% block img %}
{% endblock %}

{% block content %}
    <h2>Sign Up</h2>
    <form action="accounts/register" method="post">{% csrf_token %}
        {{form}}
        <input type="submit" value="Sign Up" />
    </form>
{% endblock %}

templates/thank_you.html
{% extends "index.html" %}
{% block img %}
{% endblock %}
{% block search %}
{% endblock %}
{% block content %}
    <div class="col s12 m12 l9">
        <div class="row">
            <div class="card feedback">
                <div class="card-content black-text">
                    <div class="card-title center-align grey-text text-darken-3">
                      <h4 class="red-text text-lighten-2"> {{form.title.value}} Has Been Successfully Added to the Library</h4>
                    </div>
                </div>
                <div><a class="view" href="{% url 'book-list' %}">View Books</a></div>

            </div>
        </div>
    </div>
{% endblock %}

templates/updated.html
{% extends "index.html" %}
{% block img %}
{% endblock %}
{% block search %}
{% endblock %}
{% block content %}
    <div class="col s12 m12 l9">
        <div class="row">
            <div class="card success feedback">
                <div class="card-content black-text">
                    <div class="card-title center-align grey-text text-darken-3">
                      <h4 class="red-text text-lighten-2"> {{form.title.value}} Has Been Successfully Edited</h4>
                    </div>
                </div>
                <div><a class="view" href="{% url 'book-list' %}">View Books</a></div>

            </div>
        </div>
    </div>
{% endblock %}